### ISSUE TITLE
Add additional method to combine multiple search engines

### ISSUE THREAD

**Issue by jgriss** [bigbio/pia#2]
Add the following method to combine search results (example expects 2):

  1. Filter each search result individually at FDR 1% (= default threshold) and add q-values
  2. Remove all PSMs with different results by the search engines
  3. Filter all PSMs that were only identified by a single search engine at q-value <= 0.1% (= high threshold)

**Comment by ypriverol** [comment]
Hi @jgriss : 
My response online: 

> Filter each search result individually at FDR 1% (= default threshold) and add q-values
This is possible easily now. I guess you want to do it before merging results? If that is the case then is done. 

> Remove all PSMs with different results by the search engines
I will implement this filter. 

> Filter all PSMs that were only identified by a single search engine at q-value <= 0.1% (= high threshold)
I will implement this filter.

**Comment by jgriss** [comment]
Hi @ypriverol 

That's exactly what I had in mind. Great! Thanks!
